name: ci

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 12 */1 * *"

permissions:
  contents: read
  id-token: write
  packages: write
  pull-requests: write
  security-events: write

jobs:
  build-edge:
    if: |
      contains(fromJson('["push","pull_request"]'), github.event_name) &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: meysam81/build-docker@main
        with:
          cosign: true
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          image-extra-tags: |
            ghcr.io/${{ github.repository }}:${{ github.run_id }}
            ghcr.io/${{ github.repository }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          image-name: ghcr.io/${{ github.repository }}
          kubescape: true
          kubescape-upload-sarif: true
          scout-cves: true

  release-please:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: release-please
        name: Release please
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple

  build-stable:
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: meysam81/build-docker@main
        with:
          cosign: true
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          image-extra-tags: |
            ghcr.io/${{ github.repository }}:${{ needs.release-please.outputs.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ needs.release-please.outputs.tag_name }}
          image-name: ghcr.io/${{ github.repository }}

  sonarcloud:
    if: |
      contains(fromJson('["push","pull_request"]'), github.event_name) &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
